# сколько надо ждатб
redemption_rate: 5

# всем или рандомна???
shared_punishment: true

rewards:
  spawn_creeper:
    reward_name: "Заспавнить Крипера" #
    message: "{user} заспавнил крипера!"
    message_failed: "Не повезло!"
    action:
      name: "spawn_entity"
      parameters:
        entity_type: "CREEPER"
        chance: 50
  clear_inventory:
    reward_name: "Очистить Инвентарь"
    message: "{user}: Стример, а где вещи?"
    message_failed: "А вещи-то на месте!"
    action:
      name: "clear_inventory"
      parameters:
        chance: 20
  add_random_effect:
    reward_name: "Рандом Эффект"
    action:
      name: "add_effect"
      parameters:
        effects: "strength:1:5s,speed:2:10s"
        is_random: true # true - выбирает один из эффектов; false - выбирает все
  drop_held_item:
    reward_name: "Дропнуть Предмет"
    action:
      name: "drop_held_item"
      parameters:
        chance: 50
  teleport_randomly:
    reward_name: "Рандом Телепорт"
    action:
      name: "teleport_nearby"
  block_sneaking:
    reward_name: "sneak"
    action:
      name: "block_action"
      parameters:
        action: "SNEAK"
        duration: 60