# Награды исполняются по очереди.
# Это контролирует время перед исполнением следующей награды, в секундах.
redemption_rate: 5

# Список наград и их действия
rewards:
  spawn_creeper: # Кодовой имя награды, должно быть разное для ВСЕХ наград
    reward_name: "Заспавнить Крипера" # Название награды на ТВИЧЕ, должно совпадать 100%
    message: "{user} заспавнил крипера!" # Сообщение, которое будет показано при исполнении этой награды
    message_failed: "Не повезло!" # Сообщение, который будет показано если награда не исполнилась ( шанс не прошел, и тд. )
    action:
      name: "spawn_entity" # Название функции которая исполниться, см. Туториал для доступных функций
      parameters: # Список параметров, для разных функций нужны свои параметры, см. Туториал
        entity_type: "CREEPER" # Тип сущности для спавна
        chance: 50 # Шанс спавна, 50% в денном случае
  clear_inventory:
    reward_name: "Очистить Инвентарь"
    message: "{user}: Стример, а где вещи?"
    message_failed: "А вещи-то на месте!"
    action:
      name: "clear_inventory"
      parameters:
        chance: 20