################################
## Файл конфигурации плагина. ##
################################

# Задержка в секундах перед тем как вызывать следующую награду.
redemption_rate: 5

# Если на сервере больше одного игрока, то награды могут выполниться либо для всех, либо рандомно.
# 'true', чтобы награды выполнялись для всех, 'false', для рандома.
shared_punishment: true

###################
## Список наград ##
###################

# Ниже можно найти примеры наград и действий.
rewards:
  # 'id' награды, должно быть разное для всех наград.

  spawn_creeper:
    # Название награды на ТВИЧЕ, которая будет вызывать это действие.
    reward_name: "Заспавнить Крипера" #

    # Сообщение, которое будет отправлено при успешном выполнении награды.
    # '{user}' будет заменено на никнейм того, кто активировал награду.
    message: "{user} заспавнил крипера!"

    # Сообщение, которое будет отправлено при НЕ успешном выполнении награды, к примеру когда шанс не сработал.
    # '{user}' будет заменено на никнейм того, кто активировал награду.
    message_failed: "Не повезло!"

    # Действие, которое будет выполнено при успешной активации.
    action:
      # Название действия, вики по всем действиям можно найти тут: https://github.com/hapyl/TwitchEvent/wiki/Events
      name: "spawn_entity"

      # Дополнительные параметры действия, для каждого действия они разные, и для некоторых их нет, см вики.
      parameters:
        # Тип сущности, который спавнить
        entity_type: "CREEPER"

        # Шанс спавна, в процентах
        chance: 50

        # Количество спавна, в данном случае случайно от 1 до 2.
        # Можно просто число: 'amount: 5', к примеру.
        amount: 1..2